### PR TITLE
Update hugo new version 0.52.0

### PR DESCRIPTION
**Pull request by trfiladelfo**
Update hugo new version 0.50
https://github.com/gohugoio/hugo/releases

### CODE REVIEW

**Comment by nikku** [comment]
Happy to take this PR into consideration if you only apply the relevant change and not your opinionated auto-formater.

**Comment by trfiladelfo** [comment]
Hello, i'm removing my auto-formatter and updated to new version hugo

**Comment by trfiladelfo** [comment]
Hello, i'm removing my auto-formatter, updated to new version hugo and verify only a new version in mocha test.

**Comment by trfiladelfo** [comment]
Hello, i'm removing my auto-formatter, updated to new version hugo and verify only a new version in mocha test.

**Comment by nikku** [comment]
Thanks for the second attempt on this PR!

I still see [a number of auto-formatter related changes](https://github.com/nikku/hugo-cli/pull/21/files) in your PR. Will close this and implement the update to `v0.52.0` myself.

**Comment by nikku** [comment]
For reference: https://github.com/nikku/hugo-cli/commit/2060d9b22556b1e9f9e676c40ac6ce5f66d35fdf is the actual commit that bumps the HUGO version.

**Comment by nikku** [comment]
Released as `v0.9.0`.

**Pull request closed without merging**
