### PR TITLE
fix executableName generation for windows

### PR DESCRIPTION
**Pull request by johann-sonntagbauer**
The executableName already containes the extension generated by the regex based placeholder replacement, so there is no need to add it again :)

### CODE REVIEW

**Comment by johann-sonntagbauer** [comment]
It seems that the extract path of the hugo binary changed as well. To make it more robust I introduced `basePath` which formulates the directory of the extracted binary files.

**Comment by nikku** [comment]
Merged the `executableName` fix via 51b60d1897c1405d259cbf08a7750c52135f9b02.

The second fix you made breaks hugo-cli on Linux. Because of that I did not merge it.

Could you provide a few details on what's wrong with the current implementation on Windows? Maybe we can fix it in a way that it works across all operating systems.

**Comment by johann-sonntagbauer** [comment]
Oh, sorry for that issue on linux. It seems that decompress creates a folder for the extracted content of the tar archive, but none for the zip archive. I will investigate that with a linux vm. 

So only on windows the path must be appended to have the same results as on linux.

**Comment by johann-sonntagbauer** [comment]
@nikku Decompressing the tar results in an directory `hugo_0.15_linux_amd64` containing the binary distribution. But the zip file does not include directories, so decompressing it will only extract the binary files without creating the directory. 
How would you like to proceed? 
1. I could ask the guys from hugo if they can include directories in the zip distribution 
2. or we can build in the creation of the directory only for windows users in hugo-cli

**Pull request closed without merging**
